export var urls: string[] = new Array(
    "128mots.com",
    "alamal-news.com",
    "apden.org",
    "arue.pf",
    "askabox.fr",
    "assurance-prevention.fr",
    "brainly.com",
    "brainly.in",
    "brainly.ro",
    "brainscape.com",
    "burgosandbrein.com",
    "calameo.com",
    "cjoint.com",
    "coin-des-animateurs.com",
    "column-care.mx",
    "commentcamarche.com",
    "commentcamarche.net",
    "commentformaterunpc.com",
    "commentouvrir.com",
    "com.mx",
    "com.py",
    "dictionary.tn",
    "diogn.fr",
    "docplayer.fr",
    "editions-delagrave.fr",
    "edu.ar",
    "ekladata.com",
    "elibrary.tips",
    "eliteanswers.in",
    "evalquiz.com",
    "exocorriges.com",
    "foforum.fr",
    "franceasks.com",
    "free.fr",
    "genevoix-signoret-vinci.fr",
    "genial.ly",
    "gouv.fr",
    "gov.ar",
    "hi7ob.com",
    "inquest.net",
    "jeuxvideo.com",
    "journaldesfemmes.com",
    "journaldunet.fr",
    "jz0ralalm.com",
    "lab-archipel.fr",
    "la-pix.fr",
    "leblogduwebmaster.fr",
    "lecoindusenior.fr",
    "lesoutrali.com",
    "lewebpedagogique.com",
    "linternaute.fr",
    "marocpolis.net",
    "mathforu.com",
    "maths-forum.com",
    "mutawakkil.com",
    "ncseonline.org",
    "nosdevoirs.fr",
    "onisep.fr",
    "onlinecv.fr",
    "openclassrooms.com",
    "pix-data.com",
    "presentation-cv-simple.com",
    "prof-tc.fr",
    "quizizz.com",
    "quiz-let.com",
    "quizlet.com",
    "quora.com",
    "reddit.com",
    "reponserapide.com",
    "scribd.com",
    "secu-ordi.com",
    "similarweb.com",
    "socialgrep.com",
    "studocu.com",
    "superhry.cz",
    "synonyme-du-mot.com",
    "taskade.com",
    "technozerrifi.com",
    "telecharger-cours.net",
    "telegra.ph",
    "tiktok.com",
    "truyenhinhcapsongthu.net",
    "twitter.com",
    "uncommonschools.org",
    "univ-pau.fr",
    "uwi.edu",
    "webflow.com",
    "xn--pixrponse-e4a.com",
    "youtube.com",
    "ystor.org",
    "z-dn.net",
);

export var pi = 3.14;
export let squareTwo = 1.41;
export const phi = 1.61;

export class RandomNumberGenerator { }

export function absolute(num: number) {
    if (num < 0) return num * -1;
    return num;
}

